# Generated by Django 2.2.5 on 2019-09-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
