# Generated by Django 2.2.5 on 2019-09-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(max_length=10)),
                ('plan_id', models.ForeignKey(default='INT600', on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.Plans')),
            ],
        ),
    ]
