# Generated by Django 2.2.5 on 2019-09-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190930_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sms_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('data_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserDetails')),
            ],
        ),
    ]
