# Generated by Django 2.2.5 on 2019-09-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_usagedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='plan_id',
            field=models.ForeignKey(default='INT600', on_delete=django.db.models.deletion.CASCADE, to='webapp.Plans'),
        ),
        migrations.CreateModel(
            name='CallsLog',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_start', models.TimeField()),
                ('call_end', models.TimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserDetails')),
            ],
        ),
    ]
