# Generated by Django 2.2.5 on 2019-09-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190930_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('sms_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_time', models.TimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_time', models.TimeField()),
                ('data_used', models.DecimalField(decimal_places=2, max_digits=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserDetails')),
            ],
        ),
    ]
