# Generated by Django 2.2.5 on 2019-09-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_datalog_smslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callslog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='datalog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='smslog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
